name: "zend-ffi tests"

on:
  push:
    branches: [ 0.9.x ]
  pull_request:
    branches: [ 0.9.x ]

jobs:
  multi:
    name: ${{ matrix.operating-system }} CI - PHP ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.4', '8.0', '8.1']
        include:
          - php-versions: '7.4'
            php-coverage: xdebug
          - php-versions: '8.0'
            php-coverage: none
          - php-versions: '8.1'
            php-coverage: none
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2, cs2pr
          extensions: ffi, opcache
          coverage: ${{ matrix.php-coverage }}
      - name: Install dependencies
        run: |
          composer install
          composer require --dev phpunit/phpunit ~8
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage/phpunit/clover.xml
      - name: Submit code coverage
        if: ${{ success() }} || ${{ failure() }}
        uses: codecov/codecov-action@v3
        with:
          file: ./clover.xml # optional
